server:
  port: 8082

api:
  base:
    path: /api/v1
app:
  internal-secret: ${INTERNAL_SECRET}
  auth-service:
    url: ${AUTH_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

spring:
  application:
    name: user-service

jwt:
  secret: ${JWT_SERCRET}
  expiration-ms: 36000000